spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}                # Kakao REST API Key (환경 변수)
            client-secret: ${KAKAO_CLIENT_SECRET}        # Kakao Client Secret (환경 변수)
            redirect-uri: "http://43.202.248.120:8080/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email       # 요청할 범위
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id                     # 사용자 식별자
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000
    refresh-expiration-time: 2592000000

aws:
  s3:
    region: ${S3_PLACE}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
