spring:
  datasource:
    username: root
    password: '0404'
    url: jdbc:mysql://localhost:3306/teamtest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000
    refresh-expiration-time: 2592000000

aws:
  s3:
    region: ${S3_PLACE}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
